---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fixicc-agent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: fixicc-agent
  serviceName: "fixicc-agent"
  template:
    metadata:
      labels:
        app: fixicc-agent
        service: fixicc-agent
    spec:
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: fixicc-agent-configs-data
        persistentVolumeClaim:
          claimName: fixicc-agent-configs-pvc
      - name: fixedge-configs-data
        persistentVolumeClaim:
          claimName: fixedge-configs-pvc
      - name: fixedge-app-logs-data
        persistentVolumeClaim:
          claimName: fixedge-app-logs-pvc          
      - name: ssh-creds-files
        secret:
          secretName: ssh-creds
          optional: true
          defaultMode: 256
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: fixicc-agent
        image: {{ .Values.fixicc_agent.image.url }}:{{ .Values.fixicc_agent.image.version }}
        resources:
{{ toYaml .Values.fixicc_agent.resources | indent 10 }}
        imagePullPolicy: {{ .Values.fixicc_agent.image.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.fixicc_agent.port }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: {{ .Values.fixicc_agent.port }}
          initialDelaySeconds: {{ .Values.fixicc_agent.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.fixicc_agent.livenessProbe.periodSeconds }}
        volumeMounts:
        - name: fixicc-agent-configs-data
          mountPath: /etc/fixicc-agent
        - name: fixedge-configs-data
          mountPath: /etc/fixedge          
        - name: fixedge-app-logs-data
          mountPath: /var/log/fixedge
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      initContainers:
        - name: git-cloner
          image: alpine/git
          resources:
            requests:
              cpu: 0.2
              memory: 100Mi
            limits:
              cpu: 0.2
              memory: 100Mi 
          args:
              - clone
              - --single-branch
              - --branch
              - {{ .Values.git_configs.branch }}
              - --
              - {{ .Values.git_configs.url }}
              - /mnt/fe-configs/data
          volumeMounts: 
            - name: "ssh-creds-files"
              mountPath: "/root/.ssh"
            - name: cache-volume
              mountPath: "/mnt/fe-configs"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false        
        - name: copy-configs
          image: busybox:1.28
          resources:
            requests:
              cpu: 0.2
              memory: 100Mi
            limits:
              cpu: 0.2
              memory: 100Mi 
          env:          
            - name: "force_init_configs"
              value: {{ .Values.force_init_configs | squote }}
          command: ['sh', '-c', '[[ "${force_init_configs}" == "true" || ! -f "/etc/fixicc-agent/agent.properties" ]] && cp -R /mnt/fe-configs/data/fixicc-agent/* /etc/fixicc-agent && echo "Copy configs - done." || echo "/etc/fixicc-agent/agent.properties already exists, skip copying..."']
          volumeMounts: 
            - name: cache-volume
              mountPath: "/mnt/fe-configs"
            - name: fixicc-agent-configs-data
              mountPath: /etc/fixicc-agent
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false              